[package]
name = "chronacle-vault"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
name = "chronacle_vault"

[dependencies]
chronacle-core = { path = "../chronacle-core" }
serde.workspace = true
async-trait.workspace = true
thiserror.workspace = true
tokio.workspace = true
yaml_serde = "0.10"

[dev-dependencies]
chronacle-core = { path = "../chronacle-core", features = ["mocks"] }
mockall.workspace = true
pretty_assertions.workspace = true
tokio.workspace = true
